version: '2.4'

x-app: &app
  build:
    context: .dockerdev
    dockerfile: Dockerfile
    args:
      ELIXIR_VERSION: '1.12.3'
      ERLANG_VERSION: '24.1.5'
  environment: &env
    MIX_ENV: ${MIX_ENV:-dev}
  image: ozfarium:1.0.0
  tmpfs:
    - /tmp
    - /app/tmp/pids

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - .dockerdev/.psqlrc:/root/.psqlrc:ro
    - .dockerdev/.bashrc:/root/.bashrc:ro
  environment:
    <<: *env
    DATABASE_URL: postgres://postgres:postgres@postgres:5432
    WEB_CONCURRENCY: 0
    HISTFILE: /app/log/.bash_history
    PSQL_HISTFILE: /app/log/.psql_history
    EDITOR: code
  depends_on:
    postgres:
      condition: service_healthy

services:
  runner:
    <<: *backend
    command: /bin/bash

  server:
    <<: *backend
    command: mix phx.server
    ports:
      - '4000:4000'

  postgres:
    image: postgres:13.5
    volumes:
      - .dockerdev/.psqlrc:/root/.psqlrc:ro
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      PSQL_HISTFILE: /root/log/.psql_history
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

volumes:
  postgres:
